# Permalinks
permalink:          pretty

# Setup
title:              darrelln
tagline:            darrelln.github.io
url:                https://darrelln.github.io
paginate:           1
baseurl:            https://darrelln.github.io

# Navigation
pages_list:
  Archive:          '/archive'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         _sass
  style:            :compressed

# About/contact
author:
  name:             darrelln
  url:              https://darrelln.github.io
  email:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
